import fs from "node:fs/promises";
import path from "node:path";
import { Workbook } from "@oai/artifact-tool";
const outDir=String.raw`C:\range_paper\05_qc\d10fb14_v01_1_work_observed_state_mixture_correction`;
const qcDir=String.raw`C:\range_paper\99_tmp\d10fb14_v01_1\artifact_tool_qc`;
const files=["B14_V01_1_ZERO_STATE_MIXTURE_SUMMARY.csv","B14_V01_1_POSITIVE_STATE_STRESS_SUMMARY.csv","B14_V01_1_HIDDEN_POSITIVE_INCIDENCE.csv","B14_V01_1_FAILURE_CONDITIONAL_SEVERITY.csv","B14_V01_1_TARGET_EQUAL_VS_EVENT_EQUAL.csv","B14_V01_1_DIRECT97_MATERIALITY_SUMMARY.csv","B14_V01_1_AB_VS_BA_SUMMARY.csv","B14_V01_1_ABIES_PROCERA_CASE.csv","B14_V01_1_STRESS_VS_AB_FOLD_DISCREPANCY.csv","B14_V01_1_DISPOSITION_MATRIX.csv","B14_V01_1_PROVENANCE.csv","B14_V01_1_INVARIANT_QC.csv","B14_V01_1_FIREWALL_QC.csv","SHA256SUMS.csv","TRANSFER_MANIFEST_v01.csv"];
await fs.mkdir(qcDir,{recursive:true});const results=[];
for(const name of files){const txt=await fs.readFile(path.join(outDir,name),"utf8");const wb=await Workbook.fromCSV(txt,{sheetName:"Data"});wb.recalculate();const inspect=await wb.inspect({kind:"workbook,sheet,table",maxChars:4500,tableMaxRows:8,tableMaxCols:14,tableMaxCellChars:100});const errors=await wb.inspect({kind:"match",searchTerm:"#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A|#NUM!|#NULL!|#SPILL!|#CALC!",options:{useRegex:true,maxResults:100},summary:`formula error scan ${name}`});const png=await wb.render({sheetName:"Data",autoCrop:"all",scale:.75,format:"png"});const pn=`${name.replace(/\.csv$/i,"")}.png`;await fs.writeFile(path.join(qcDir,pn),new Uint8Array(await png.arrayBuffer()));const et=String(errors.ndjson??"");if(/#REF!|#DIV\/0!|#VALUE!|#NAME\?|#N\/A|#NUM!|#NULL!|#SPILL!|#CALC!/.test(et))throw new Error(`Spreadsheet error marker in ${name}`);results.push({file:name,preview:path.join(qcDir,pn),inspect:String(inspect.ndjson??"").slice(0,4500),status:"PASS"});}
await fs.writeFile(path.join(qcDir,"artifact_tool_csv_verification.json"),JSON.stringify({artifactTool:"@oai/artifact-tool",files:results,status:"PASS"},null,2));console.log(JSON.stringify({status:"PASS",verifiedCsvFiles:results.length,qcDir},null,2));
